# Generated by Django 3.2.23 on 2023-11-23 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_accountstatus_user_name'),
        ('profiles', '0015_auto_20180423_0727'),
    ]

    operations = [
    ]
